<?php 
ob_start();
include("../../sessionControl.php");
include("../../database.php"); ?>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<link rel="STYLESHEET" href="../print_static.css" type="text/css" />
<link rel="STYLESHEET" href="../../css/font-awesome.min.css" type="text/css" />

</head>

<body>

<div id="body">

<div id="section_header">
</div>

<div id="content">
  
<div class="page" style="font-size: 7pt">
<table style="width: 100%;" class="header">
<tr>
<td><h1 style="text-align: left">BRANCH WISE TRANSACTION SUMMARY</h1></td>
<td><h1 style="text-align: right"></h1></td>
</tr>
</table>

<table style="width: 100%; font-size: 8pt;">
<tr>
<td>Starting Date: <strong><?php echo $_GET['frm']; ?></strong></td>
<td>Generation Date: <strong><?php echo date("Y-m-d");?></strong></td>
</tr>

<tr>
<td>Ending Date: <strong><?php echo $_GET['to']; ?></strong></td>
<td>Generated By: <strong><?php echo $_SESSION['username']; ?></strong></td>
</tr>

</table>

<table style="width: 100%; border-top: 1px solid black; border-bottom: 1px solid black; font-size: 8pt;">
<tr>
<td></td>
<td align="right"><i class="fa fa-file-excel-o">&nbsp;</i><a href='<?php echo "brSumRptXl.php?".$_SERVER['QUERY_STRING'];?>'>Export To Excel</a></td>
</tr>
 

</table>


<?php
$frmStr="";
$toStr="";
$frm=$_GET['frm'];
$to=$_GET['to'];

if($_GET['frm'][2]=='/')
{
$frmStr=explode('/', $_GET['frm']);
$frm=$frmStr[2]."-".$frmStr[0]."-".$frmStr[1];
}
if($_GET['to'][2]=='/')
{
$toStr=explode('/', $_GET['to']);
$to=$toStr[2]."-".$toStr[0]."-".$toStr[1];
}


$brSelected=$_GET['br'];
?>
					 

<table class="change_order_items">

<tr><td colspan="9" style="height: 25px"><h2>Transaction Summary:</h2></td></tr>

<tbody>
<tr>
					<th style="text-align: center; width: 40px;" rowspan="2">SL</th>
						
						<th style="width: 407px" rowspan="2">&nbsp;BRANCH</th>
						<th align="center" colspan="3">
							OUTWARD</th>

					
						<th colspan="3">INWARD</th>
						<th class="change_order_total_col" rowspan="2">NET BALANCE</th>

						</tr>
						
						<tr class="odd_row">
						<th align="center" style="width: 63px; height: 16px;">
							No. Tran.</th>

					
						<th align="center" style="width: 155px; height: 16px;">
							Credit 
							Amt.</th>

					
						<th align="center" style="width: 161px; height: 16px;">
							Debit 
							Amt.</th>

					
						<th class="change_order_total_col" style="width: 63px; height: 16px;">
							No. Tran.</th>

					
						<th class="change_order_total_col" style="width: 158px; height: 16px;">
						Credit</th>

					
						<th class="change_order_total_col" style="width: 161px; height: 16px;">
						Debit</th>

						</tr>
						
 
					<?php 
					$sl=0;
					
					//outward vars...................
					$crAmtOut=0;
					$drAmtOut=0;
					
					$tCrAmtOut=0;
					$tDrAmtOut=0;
					$tcntOut=0;
					
					
					// INward Vars.........................
					$CrAmtIn=0;
					$tCrAmtIn=0;
					
					$tCntIn=0;
					
					$tInDr=0;
					$DrAmtIn=0;
					
					
					//net vars...............
					$tNet=0;
					$net=0;
					
				 
						$q=mysql_query("select * from branch_transaction_point where keyCode in ($brSelected) order by name");
						while($r=mysql_fetch_array($q))
						{
						  
						  echo $brCode=$r['keyCode'];
						  $brRouting=$r['routingNumber'];

						  
						  
						  $qOutDr=mysql_query("select SUM(CdtTrfTxInf_IntrBkSttlmAmt) amt, COUNT(keyCode) cnt from out_credit_transfer where status='4' and trnDate between '$frm' and '$to' 
							and maker in (select username from members where branch='$brCode')");
							$qOutDrR=mysql_fetch_array($qOutDr);
						  
						  $qOutDrConf=mysql_query("select SUM(CdtTrfTxInf_IntrBkSttlmAmt) amt from out_credit_transfer where status='4' and trnDate between '$frm' and '$to' 
							and maker in (select username from members where branch='$brCode') and AppHdr_BizMsgIdr in (select NtfctnNtryNtryRef from in_debit_confirmation)");
							
						  $qOutDrConfR=mysql_fetch_array($qOutDrConf);
							
						 
						 
						 $qInCr=mysql_query("select SUM(NtfctnNtryAmt) amt, COUNT(keyCode) cnt from in_credit_confirmation where 
							NtfctnNtryNtryRef in (
							select GrpHdr_MsgId from in_copy_of_transfer where CdtTrfTxInf_CdtrAgt_BranchId_Id='$brRouting' and CdtTrfTxInf_IntrBkSttlmDt between '$frm' and '$to' UNION
							select GrpHdr_MsgId from in_copy_of_transfer_fi_fi where CdtTrfTxInf_Cdtr_BrnchId_Id='$brRouting' and CdtTrfTxInf_IntrBkSttlmDt between '$frm' and '$to' UNION
							select GrpHdr_MsgId from in_pac_4 where OrgnlGrpInf_OrgnlMsgId in (select AppHdr_BizMsgIdr from out_credit_transfer where trnDate between '$frm' and '$to' and CdtTrfTxInf_DbtrAgt_BrnchId_Id='$brRouting')
							)");
							$qInCrR=mysql_fetch_array($qInCr);
							
						  $qInDr=mysql_query("select SUM(TxInf_RtrdIntrBkSttlmAmt) amt from outward_return where status='R' and trnDate between '$frm' and '$to' 
							and TxInf_OrgnlTxRef_CdtrAgt_BrnchId_Id='$brRouting'");
							
							$qInDrR=mysql_fetch_array($qInDr);


						?>
					
					
					<tr class="odd_row">
					<td style="text-align: center; width: 40px;"><?php echo ++$sl;?></td>
						
						<td style="width: 407px"><?php echo $r['name']?></td>
						<td align="right" style="width: 63px"><?php echo $qOutDrR['cnt']; $tcntOut=$tcntOut+$qOutDrR['cnt']; ?></td>

					
						<td align="right" style="width: 155px">
							<?php
							
							
							echo $crAmtOut=sprintf('%.2f', $qOutDrR['amt']-$qOutDrConfR['amt']);
							
							$tCrAmtOut=$tCrAmtOut+$crAmtOut;
							?>
							
							</td>

					
						<td align="right" style="width: 161px">
							
							<?php
							
							
							echo $drAmtOut=sprintf('%.2f', $qOutDrR['amt']);
							
							$tDrAmtOut=$tDrAmtOut+$drAmtOut;
							
							
							
							?>
							</td>

					
						<td class="change_order_total_col" style="width: 63px">
						<?php echo $qInCrR['cnt']; $tCntIn=$tCntIn+$qInCrR['cnt']?></td>

					
						<td class="change_order_total_col" style="width: 158px">
						<?php
						echo $CrAmtIn=sprintf('%.2f', $qInCrR['amt']);
						$tCrAmtIn=$tCrAmtIn+$CrAmtIn;
						?>
						
						</td>

					
						<td class="change_order_total_col" style="width: 161px">
						<?php
						echo $DrAmtIn=sprintf('%.2f', $qInDrR['amt']);
						
						$tInDr=$tInDr+$DrAmtIn;
						?>
						</td>
						<td class="change_order_total_col"><?php
						echo $net=sprintf('%.2f', ($CrAmtIn-$DrAmtIn)-($qOutDrConfR['amt']));
						
						$tNet=$tNet+$net;
						?></td>
						
						</tr>

						
							<?php
				 	 	}
						?>


					

 
<!--
<tr class="odd_row">
<td style="text-align: center">2</td>
<td>Cogs (Cylindrical)</td>
<td style="text-align: center">45</td>
<td style="text-align: right; border-right-style: none;">$25.00</td>
<td class="change_order_unit_col" style="border-left-style: none;">Ea.</td>
<td class="change_order_total_col">$1125.00</td>
</tr>

 -->

					<tr class="odd_row" style=" font-weight:bold">
					<td style="text-align: center; width: 40px;"></td>
						
						<td style="width: 407px"></td>
						<td align="right" style="width: 63px"><?php echo $tcntOut;?></td>

					
						<td align="right" style="width: 155px">
							<?php echo sprintf('%.2f',$tCrAmtOut);?></td>

					
						<td align="right" style="width: 161px"><?php echo sprintf('%.2f', $tDrAmtOut)?></td>

					
						<td class="change_order_total_col" style="width: 63px"><?php echo $tCntIn; ?></td>

					
						<td class="change_order_total_col" style="width: 158px">
						<?php echo sprintf('%.2f', $tCrAmtIn)?></td>

					
						<td class="change_order_total_col" style="width: 161px">
						<?php
						echo sprintf('%.2f', $tInDr);
						?></td>
						<td class="change_order_total_col"><?php
						echo sprintf('%.2f', $tNet);
						?></td>

						</tr>
						
</tbody>




</table>


</div>




<div class="page" style="font-size: 7pt">

<table class="sa_signature_box" style="border-top: 1px solid black; padding-top: 2em; margin-top: 2em;">

  <tr>    
    <td>Concern Officer:</td><td class="written_field" style="padding-left: 2.5in">&nbsp;</td>
    <td style="padding-left: 1em">In-Charge:</td><td class="written_field" style="padding-left: 2.5in; text-align: right;"></td>
  </tr>
  <tr>
    <td colspan="3" style="padding-top: 0em">&nbsp;</td>
    <td style="text-align: center; padding-top: 0em;"></td>
  </tr>

<tr><td colspan="4" style="white-space: normal">
This is system generated report.  
</td>
</tr>

<tr>
<td colspan="2">Generated By <?php echo $_SESSION['username'];?> On <?php echo date('Y-m-d')?>
</td>

<td colspan="2" style="padding-left: 1em;">
</td>
</tr>
</table>

</div>


</div>
</div>

</body>
</html>
<?php
 
$HTMLoutput = ob_get_contents();
ob_end_clean();

//==============================================================
//==============================================================
include("../pdf/mpdf.php");

//$mpdf=new mPDF('c','A4','','',32,25,27,25,16,13);

$mpdf=new mPDF('c','A4-L');

$mpdf->SetDisplayMode('fullpage');

$mpdf->list_indent_first_level = 0;	// 1 or 0 - whether to indent the first level of a list
// LOAD a stylesheet
$stylesheet = file_get_contents('../print_static.css');
$stylesheet = $stylesheet.file_get_contents('../../css/font-awesome.min.css');
//$stylesheet = $stylesheet.file_get_contents('mpdfstyletables.css');


$mpdf->WriteHTML($stylesheet,1); // The parameter 1 tells that this is css/style only and no body/html/text
$mpdf->WriteHTML($HTMLoutput,2);
$mpdf->SetProtection(array('copy','print'), '123456', '123456');
$mpdf->Output('BR_SUM_RPT.pdf','I'); // use 'I' to show in Browser
exit;
//==============================================================
//==============================================================
//==============================================================
?>

 
			

